### PR TITLE
Replace PHPExcel with PhpSpreadsheet

### PR DESCRIPTION
**Pull request by ghost**
## **Replaced PHPExcel with PhpSpreadsheet**
Replaced deprecated PHPExcel package with its successor PhpSpreadsheet (made by the same author) according to the dedicated upgrade/migration guide [PhpSpreadsheet - migration from PHPExcel](https://phpspreadsheet.readthedocs.io/en/develop/topics/migration-from-PHPExcel/#migration-from-phpexcel)
The upgrade was performed by an automated tool provided by PhpSpreadsheet.

### CODE REVIEW

**Comment by mikehaertl** [comment]
@matijadg Thanks, this looks good. I was planning to update this anyway but had no time yet. I'll merge it as soon as I find some time to test it locally. Did you also test if everything still works as expected?

Oh and just in case: If you planned to also migrate https://github.com/codemix/yii2-excelexport to the new package - please wait. I will probably rewrite that class a little during that process.

**Comment by ghost** [comment]
@mikehaertl I did some small non-formal tests while debugging and everything was working as expected. But I will also write proper tests within few days, since I have to do it anyway (in order to merge any PRs containing package changes in our company's internal Yii framework repo, tests must be written).

**Comment by mikehaertl** [comment]
Ok, thanks. If you want to contribute some tests, that would be great. But please try to keep it easy :). Testing this thing can be quite some work, given all the options.

**Comment by mikehaertl** [comment]
@matijadg I just released 1.1.0 containing this change. Maybe you can also do a quick test if everything works as expected.

Thanks again for your help.

**Pull request merged**
